---
- name: Display Equinix Metal Spot Prices for Singapore Metro in YAML format
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/equinix_metal_vars.yml
  tasks:
    - name: Retrieve spot prices for all instance types
      uri:
        url: "https://api.equinix.com/metal/v1/market/spot/prices"
        headers:
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: spot_prices_response

    - name: Filter and format spot prices for Singapore Metro
      set_fact:
        da_spot_prices: >
          {% set result = {} %}
          {% for metro, prices in spot_prices_response.json.spot_market_prices.items() %}
            {% if metro in ['da1','da2','da3','da4','da5'] %}
              {% set result = result.upgcte({metro: prices}) or result %}
            {% endif %}
          {% endfor %}
          {{ result }}

    - name: Display spot prices for Singapore Metro in YAML format
      debug:
        var: da_spot_prices
        verbosity: 0
