---
- name: Display Equinix Metal Spot Prices for Silicon Valley Metro in YAML format
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/equinix_metal_vars.yml
  tasks:
    - name: Retrieve spot prices for all instance types
      uri:
        url: "https://api.equinix.com/metal/v1/market/spot/prices"
        headers:
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: spot_prices_response

    - name: Filter and format spot prices for Silicon Valley Metro
      set_fact:
        silicon_valley_spot_prices: >
          {% set result = {} %}
          {% for metro, prices in spot_prices_response.json.spot_market_prices.items() %}
            {% if metro in ['sv1', 'sv2', 'sv3', 'sv4', 'sv5', 'sv6', 'sv7', 'sv8', 'sv9', 'sv10', 'sv11', 'sv12', 'sv13', 'sv14', 'sv15', 'sv16', 'sv17'] %}
              {% set result = result.update({metro: prices}) or result %}
            {% endif %}
          {% endfor %}
          {{ result }}

    - name: Display spot prices for Silicon Valley Metro in YAML format
      debug:
        var: silicon_valley_spot_prices
        verbosity: 0
